import react from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Heading from '../components/Heading'
import { FaFacebookF, FaLinkedinIn, FaGoogle, FaRegEnvelope } from 'react-icons/fa';
import {MdLockOutline} from 'react-icons/md';
import { render } from 'react-dom';

class Loginform extends react.Component {
    render()
    {
    return (
    <div className='flex flex-col items-center justify-center min-h-screen py-2 bg-gray-200'>
      <Head>
        <title>Login HOme page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className='flex flex-col items-center justify-center w-full flex-1 px-20 text-center'>
       
         <div className='w-3/5 p-5 bg-white rounded-2xl'>
           <div className='text-left font-bold '>
             <span className='text-green-500'>SAC PORTAL </span>IIT JAMMU
             </div>
             <div className='py-10'>
               <h2 className='text-3xl text-center font-bold text-green-500 mb-2'>Sign in to account</h2>
              
               <div className='flex justify-center my-2'>
                 <a href="#" className='border-2 border-gray-200 rounded-full p-3 mx-1'>
                     <FaFacebookF className='text-sm'/>
                 </a>
                 <a href="#" className='border-2 border-gray-200 rounded-full p-3 mx-1'>
                     <FaLinkedinIn className='text-sm'/>
                 </a>
                 <a href="#" className='border-2 border-gray-200 rounded-full p-3 mx-1'>
                     <FaGoogle className='text-sm'/>
                 </a>
               </div>
               
               <p className='text-gray-400 my-3'>OR</p>

               <div className='flex flex-col items-center mb-3'>
                 <div className='bg-gray-100 w-64 p-2 flex items-center mb-3'>
                   <FaRegEnvelope className='text-gray-400 mr-2'/>
                   <input type="email" name='email' placeholder='Email' className='bg-gray-100 outline-none test-sm flex-1'/>
                   </div>

                 <div className='bg-gray-100 w-64 p-2 flex items-center mb-3'>
                   <MdLockOutline className='text-gray-400 mr-2'/>
                   <input type="password" name='passwd' placeholder='Password' className='bg-gray-100 outline-none test-sm flex-1'/>
                   </div>

                  <div className='flex justify-between w-64 mb-5'>
                    <label className='flex items-center text-xs'>
                      <input type="checkbox" name='remember' className='mr-2'/>Remember me
                    </label>
                    <a href="#" className='text-xs'>Forgot Password</a>
                  </div>
                  <div className='flex'>
                  <a href="#" className='border-2 border-green rounded-full px-10 py-2 inline-block font-semibold hover:bg-green-500 hover:text-white mr-1'>Sign In
                  </a>
                  <a href="#" className='border-2 border-green rounded-full px-10 py-2 inline-block font-semibold hover:bg-green-500 hover:text-white'>Register
                  </a>
                  </div>
                 

            </div>
            
         
             </div>
           </div>
      </main>
    </div>
  )
    }
}

export default Loginform