import Head from 'next/head'
import Image from 'next/image'
import Heading from '../components/Heading'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className='text-4xl'>S.A.C</p>
      <Heading heading={"spider8019"}/>

      <p>integrated with tailwind.css</p>
      <p>you can choose any light weight package to ease your task.</p>
    </div>
  )
}
